version: "3.8"
services:
  graphdb:
    image: "neo4j:enterprise"
    network_mode: bridge
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ../.neo4j/data:/data
