version: "3.9"
services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.1.0
    environment:
      OPENSEARCH_HOSTS: '["https://host.docker.internal:9201"]'
    ports:
      - "5601:5601"
