version: "3.8"
services:
  postgres:
    image: postgres:10.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: devbox
      POSTGRES_USER: devbox
      POSTGRES_PASSWORD: devbox
