version: '3.8'
services:
  greenmail:
    image: greenmail/standalone:1.5.14
    restart: always
    ports:
      - 3025:3025 # SMTP
      - 3110:3110 # POP3
      - 3143:3143 # IMAP
      - 3465:3465 # SMTPS
      - 3993:3993 # IMAPS
      - 3995:3995 # POP3S
    environment:
      GREENMAIL_OPTS: '-Dgreenmail.setup.test.all
                         -Dgreenmail.hostname=0.0.0.0
                         -Dgreenmail.verbose
                         -Dgreenmail.users=admin:admin@localhost.test,confluence:confluence@localhost.test'
      JAVA_OPTS: '-Djava.net.preferIPv4Stack=true -Xmx512m'
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: devbox
      POSTGRES_USER: devbox
      POSTGRES_PASSWORD: devbox