version: "3.8"
services:
  postgres:
    image: postgres:10.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: confluence
      POSTGRES_PASSWORD: confluence
  confluence:
    image: ubuntu:18.04
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:/sources
    ports:
      - "8090:8090"
    links:
      - "postgres"
