version: "3.7"
services:
  postgres:
    image: postgres:10.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PRODUCT}
      POSTGRES_USER: ${PRODUCT}
      POSTGRES_PASSWORD: ${PRODUCT}
